Tweak messages, errors, and exits

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -3,10 +3,25 @@
 source "$(dirname "$0")/utils.sh"
 
 http_download() {
-  local url=$1
-  local file=$2
-  local tmp_file="${file}/rakudo.tar.gz.$(date +%s)"
+  local version=$1
+  local path=$2
+  local install_type=$3
+
+  local url="$(download_url $version)"
+
+  if [ "$install_type" != "version" ]; then
+    echo "Install type '$install_type' not supported."
+    exit 1
+  fi
+
+  if [ -z "$url" ]; then
+    echo "URL not found for version '$version'."
+    exit 1
+  fi
+
+  local tmp_file="${path}/rakudo.tar.gz.$(date +%s)"
   local ret=1
+  echo "Downloading $url to ${path}/rakudo.tar.gz ..."
   if curl --version &>/dev/null; then
     curl -fsSL -o $tmp_file $url
     ret=$?
@@ -14,14 +29,17 @@ http_download() {
     wget -q -O $tmp_file $url
     ret=$?
   else
-    die "Need curl or wget"
+    echo "'curl' or 'wget' required."
+    exit 1
   fi
   if [[ $ret -eq 0 ]]; then
-    mv $tmp_file "${file}/rakudo.tar.gz"
+    mv $tmp_file "${path}/rakudo.tar.gz"
+    echo "Download complete!"
   else
     rm -f $tmp_file
-    return 1
+    echo "Download error. Exiting."
+    exit 1
   fi
 }
 
-http_download "$(download_url $ASDF_INSTALL_VERSION)" $ASDF_DOWNLOAD_PATH
+http_download $ASDF_INSTALL_VERSION $ASDF_DOWNLOAD_PATH $ASDF_INSTALL_TYPE
